### ISSUE TITLE
ZMQ errors printed on BlueSky exit

### ISSUE THREAD

**Issue by RubenJacobse** [TUDelft-CNS-ATM/bluesky#219]
When exiting BlueSky through the GUI on Ubuntu 18.04 the following errors are printed to the console:

```
Loading texture data/graphics/world.16384x8192.dds
Client b'\x00\x1f\xfbi\xe5' connected to host b'\x00\xe5u\xd5_'
BlueSky normal end.
BlueSky normal end.
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa597ad180>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa597ad250>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa785536c8>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa78553ce0>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa78553c78>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x7faa78553d48>>
Traceback (most recent call last):
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 67, in __del__
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/socket.py", line 105, in close
  File "/home/ruben/.virtualenvs/bsky/lib/python3.6/site-packages/zmq/sugar/context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
```

**Comment by jooste** [comment]
this seems to be resolved in newer versions of pyzmq
