### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'dict' and 'int'

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#228]
![Capture](https://user-images.githubusercontent.com/29206618/78688281-01bd8000-78ed-11ea-8068-bc4b055dc0be.PNG)
Im trying to use tensorforce for my RL agent and whenever I import tensorforce it causes the system to crash with this Trace:
```
Traceback (most recent call last):
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\network\client.py", line 124, in receive
    self.stream(strmname, pydata, sender_id)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\network\client.py", line 61, in stream
    self.stream_received.emit(name, data, sender_id)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\tools\signal.py", line 15, in emit
    subs(*args, **kwargs)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 625, in on_simstream_received
    self.update_aircraft_data(self.acdata)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 705, in update_aircraft_data
    update_buffer(self.aclatbuf, np.array(data.lat[:MAX_NAIRCRAFT], dtype=np.float32))
TypeError: unhashable type: 'slice'
```
Any idea what the problem is/work around?

Edit: Added screenshot of full trace {[https://imgur.com/a/0CLrUbk](https://imgur.com/a/0CLrUbk)}

**Comment by Ellislee1** [comment]
Edit 2: After pulling the most recent version of BlueSky I now get a new error
![Capture](https://user-images.githubusercontent.com/29206618/78716114-4b6e9080-7916-11ea-8f98-19ab4a6beeb7.PNG)
```
Traceback (most recent call last):
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\network\client.py", line 124, in receive
    self.stream(strmname, pydata, sender_id)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\network\client.py", line 61, in stream
    self.stream_received.emit(name, data, sender_id)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\tools\signal.py", line 15, in emit
    subs(*args, **kwargs)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 625, in on_simstream_received
    self.update_aircraft_data(self.acdata)
  File "E:\Undergraduate-Dissertation\Undergraduate-Dissertation\bluesky-master\bluesky\ui\qtgl\radarwidget.py", line 706, in update_aircraft_data
    np.sin(data.asastrk / 180 * np.pi), 0.0)
TypeError: unsupported operand type(s) for /: 'dict' and 'int'
```

**Comment by jooste** [comment]
Hi,

The error you mention indicates that data.asastrk is of type `dict`. Normally in BlueSky this is a numpy array (see e.g., bluesky/traffic/resolution.py, line 31). The fact that it's a dict when you run it probably means that your code changes the type of this variable. since you are doing CD&R this indeed seems likely.

**Comment by Ellislee1** [comment]
Hi Jooste,
Could you explain what you mean by CD&R?

**Comment by jooste** [comment]
CD&R stands for Conflict Detection and Resolution, i.e., keeping aircraft at a safe distance from each other. From your description I assumed that you are either subclassing `ConflictResolution`, or have changed one of the current implementations.
