### ISSUE TITLE
AttributeError: 'PerfBADA' object has no attribute 'show_performance'

### ISSUE THREAD

**Issue by ZhuKe423** [TUDelft-CNS-ATM/bluesky#230]
in stack.py , the 'PERF' command has defined to call the bs.traf.perf.show_performance, but in the BADA model, the perfbada doesn't have the this _show_performance_  member function.

log:
Successfully loaded plugin DATAFEED
Traceback (most recent call last):
  File "BlueSky.py", line 115, in <module>
    main()
  File "BlueSky.py", line 76, in main
    bs.init(mode, discovery=discovery, cfgfile=cfgfile, scnfile=scnfile)
  File "D:\MyProject\bluesky\bluesky\__init__.py", line 90, in init
    stack.init(scnfile)
  File "D:\MyProject\bluesky\bluesky\stack\stack.py", line 613, in init
    bs.traf.perf.show_performance,
AttributeError: 'PerfBADA' object has no attribute 'show_performance'
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x0F777FB0>>
Traceback (most recent call last):
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\socket.py", line 105, in close
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Exception ignored in: <bound method Socket.__del__ of <zmq.sugar.socket.Socket object at 0x0F7A3030>>
Traceback (most recent call last):
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\socket.py", line 67, in __del__
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\socket.py", line 105, in close
  File "D:\Apps\Python\Python36\lib\site-packages\zmq\sugar\context.py", line 153, in _rm_socket
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "D:\MyProject\bluesky\bluesky\network\client.py", line 90, in receive
    def receive(self, timeout=0):
KeyboardInterrupt

**Comment by ProfHoekstra** [comment]
Thanks for pointing this out, Zhu Ke! We’ll fix this immediately.

**Comment by ProfHoekstra** [comment]
PERF command added to BADA. In both BADA en OpenAP units changed to aeronautical units..
