### ISSUE TITLE
Cachefile not found error for BlueSky.py

### ISSUE THREAD

**Issue by weiguowilliam** [TUDelft-CNS-ATM/bluesky#234]
When I first run BlueSky.py, it shows this error:
Cachefile not found: data/cache\py3\aptsurface.p.

I can run BlueSky_pygame.py successfully. Also, I can install bluesky.exe successfully. I checked and my laptop supports OpenGL 3.3. Also, check.py runs well.

I wonder what the reason is? Thank you so much for your help.

The whole log is as follow:
Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Accepting event connections on port 11000, and stream connections on port 11001
Discovery is disabled
Loading palette bluesky-default
Reading config from settings.cfg
Using Python-based geo functions
Loading global navigation database...
Reading cache: data/cache\py3\navdata.p
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Using Qt 5.15.0 for windows and widgets
Using Open Aircraft Performance (OpenAP) model
Qt gui warning: Unable to open default EUDC font: "C:\\Users\\jason\\AppData\\LocalLow\\SogouPY\\EUDC\\SGPYEUDC_1.TTE"
QGLWidget initialized for OpenGL version 3.3
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
Cachefile not found: data/cache\py3\aptsurface.p
Reading apt.dat from apt.zip
Traceback (most recent call last):
  File "D:\bluesky\bluesky\navdatabase\loadnavdata.py", line 49, in load_aptsurface
    vbuf_asphalt  = cache.load()
  File "D:\bluesky\bluesky\tools\cachefile.py", line 47, in load
    self.check_cache()
  File "D:\bluesky\bluesky\tools\cachefile.py", line 32, in check_cache
    raise CacheError('Cachefile not found: ' + self.fname)
bluesky.tools.cachefile.CacheError: Cachefile not found: data/cache\py3\aptsurface.p

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\BlueSky.py", line 115, in <module>
    main()
  File ".\BlueSky.py", line 99, in main
    qtgl.start(mode)
  File "D:\bluesky\bluesky\ui\qtgl\gui.py", line 68, in start
    win = MainWindow(mode)
  File "D:\bluesky\bluesky\ui\qtgl\mainwindow.py", line 102, in __init__
    self.radarwidget = RadarWidget()
  File "D:\bluesky\bluesky\ui\qtgl\radarwidget.py", line 141, in __init__
    self.apt_ctrlat, self.apt_ctrlon, self.apt_indices = load_aptsurface()
  File "D:\bluesky\bluesky\navdatabase\loadnavdata.py", line 59, in load_aptsurface
    apt_ctr_lon, apt_indices = load_aptsurface_txt()
  File "D:\bluesky\bluesky\navdatabase\load_visuals_txt.py", line 189, in load_aptsurface_txt
    cur_poly.addVertex(vertex, controlpoint)
  File "D:\bluesky\bluesky\ui\polytools.py", line 68, in addVertex
    glu.gluTessVertex(PolygonSet.tess, vertex, vertex)
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\OpenGL\GLU\tess.py", line 188, in gluTessVertex
    return tess.gluTessVertex( location, data )
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\OpenGL\GLU\tess.py", line 68, in gluTessVertex
    location = arrays.GLdoubleArray.asArray( location, GL_1_1.GL_DOUBLE )
  File "src/arraydatatype.pyx", line 172, in OpenGL_accelerate.arraydatatype.ArrayDatatype.asArray
  File "src/arraydatatype.pyx", line 47, in OpenGL_accelerate.arraydatatype.HandlerRegistry.c_lookup
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\OpenGL\plugins.py", line 16, in load
    return importByName( self.import_path )
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\OpenGL\plugins.py", line 38, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\OpenGL\arrays\numpymodule.py", line 27, in <module>
    from OpenGL_accelerate.numpy_formathandler import NumpyHandler
  File "src/numpy_formathandler.pyx", line 55, in init OpenGL_accelerate.numpy_formathandler
  File "D:\programs\anaconda\envs\bluesky\lib\site-packages\numpy\__init__.py", line 214, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'

**Comment by jooste** [comment]
Hi, 

The error you're seeing related to the cache is not an error, but a side-effect of bluesky prematurely quitting due to a different error. The problem you have is a faulty pyopengl-accelerate installation. This generates the `module 'numpy' has no attribute 'float128'` error. A solution would be to update your pyopengl installation, or remove the pyopengl-accelerate package.

**Comment by weiguowilliam** [comment]
> Hi,
> 
> The error you're seeing related to the cache is not an error, but a side-effect of bluesky prematurely quitting due to a different error. The problem you have is a faulty pyopengl-accelerate installation. This generates the `module 'numpy' has no attribute 'float128'` error. A solution would be to update your pyopengl installation, or remove the pyopengl-accelerate package.

Thank you so much! Updating Pyopengl works!
