### ISSUE TITLE
Unable to launch Bluesky in Ubuntu

### ISSUE THREAD

**Issue by hemjyoti** [TUDelft-CNS-ATM/bluesky#301]
Hello,

I am trying to run Bluesky in Ubuntu 16.04. I have all the installation instructions and updated all the desired libraries. The Bluesky GUI does start but it is completely blank with a black screen. I would also like to mention that my BADA perfromance folder was empty as I could not find zip folder as mentioned in the readme file.  I am able to load the aircrafts using the command line but I do not see any change in the screen. However, I get the following error while running it:
Loading texture data/graphics/world.16384x8192.dds
Error while creating RadarWidget objects: <built-in method asArray of OpenGL_accelerate.arraydatatype.ArrayDatatype object at 0x7fe5ab8d68b8> returned a result with an error set
Failed to load BADA performance model
ND: Context not valid in create_objects, or shareWidget not yet initialized
Client b'\x00\xd1\xb01\n' connected to host b'\x00\xb0+gW'
ND: Context not valid in create_objects, or shareWidget not yet initialized
ND: Context not valid in create_objects, or shareWidget not yet initialized
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED
ND: Context not valid in create_objects, or shareWidget not yet initialized
ND: Context not valid in create_objects, or shareWidget not yet initialized

Can you please help me with it ? Thanking you in advance.

**Comment by hemjyoti** [comment]
However, when I try to launch the BLuesky-pygame version, it does run without any issue. So may be my issue has something to do with the pyqt version.

**Comment by jooste** [comment]
Hello, and welcome to BlueSky!

Your error looks like an issue with PyOpenGL. It also seems like you are not running the most recent version of BlueSky, am I correct? The line "Error while creating RadarWidget" objects is no longer printed on construction errors in the current version. 

There have been many problems with PyOpenGL (accelerate), which is why in the current version of BlueSky we try to rely only on the OpenGL functions provided by the PyQt library. You could try to run the current version of BlueSky to see if that resolves your error.

**Comment by hemjyoti** [comment]
Thank you professor for your quick reply ! Indeed, I am using a old version of Bluesky from which I was able to run the Bluesky-pygame successfully.

Now coming to the Qtgl based Bluesky for the current version, I just pulled the repo from git today, and now I get the following error now :  

Reading magnetic variation data
Traceback (most recent call last):
  File "BlueSky.py", line 115, in <module>
    main()
  File "BlueSky.py", line 105, in main
    raise error
  File "BlueSky.py", line 98, in main
    from bluesky.ui import qtgl
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.glhelpers import (gl, RenderObject, RenderTarget, RenderWidget,
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.gui import start
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/gui.py", line 9, in <module>
    from bluesky.ui.qtgl.mainwindow import MainWindow, Splash, DiscoveryDialog
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/mainwindow.py", line 21, in <module>
    from bluesky.ui.qtgl.radarwidget import RadarWidget
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/radarwidget.py", line 10, in <module>
    import bluesky.ui.qtgl.glhelpers as glh
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/glhelpers.py", line 5, in <module>
    from typing import OrderedDict
ImportError: cannot import name 'OrderedDict'

**Comment by jooste** [comment]
That seems to indicate that you are using a version of python that is too old. Could you check which version you are using? (`python --version`).

**Comment by hemjyoti** [comment]
I am using Python 3.6.9 in Anaconda. Specifically, this is the output I get from python --version
Python 3.6.9 :: Anaconda, Inc.

**Comment by jooste** [comment]
Oh, and do another update, the `from typing import OrderedDict` should've been `from collections import OrderedDict`. Seems like smart IDE's don't always autocomplete imports correctly ;)

**Comment by hemjyoti** [comment]
Now I get the following errors :  
One related to ZMQError and the other being related to attribute 'ui'

   *****   BlueSky Open ATM simulator *****
Distributed under GNU General Public License v3
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/hemjyoti/anaconda3/envs/MAHALO_RL_python3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/network/server.py", line 74, in run
    self.fe_event.bind(f'tcp://*:{bs.settings.event_port}')
  File "/home/hemjyoti/.local/lib/python3.6/site-packages/zmq/sugar/socket.py", line 172, in bind
    super().bind(addr)
  File "zmq/backend/cython/socket.pyx", line 540, in zmq.backend.cython.socket.Socket.bind
  File "zmq/backend/cython/checkrc.pxd", line 28, in zmq.backend.cython.checkrc._check_rc
zmq.error.ZMQError: Address already in use

Loading palette bluesky-default
Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
Traceback (most recent call last):
  File "BlueSky.py", line 115, in <module>
    main()
  File "BlueSky.py", line 98, in main
    from bluesky.ui import qtgl
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.glhelpers import (gl, RenderObject, RenderTarget, RenderWidget,
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.gui import start
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/gui.py", line 9, in <module>
    from bluesky.ui.qtgl.mainwindow import MainWindow, Splash, DiscoveryDialog
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/mainwindow.py", line 21, in <module>
    from bluesky.ui.qtgl.radarwidget import RadarWidget
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/radarwidget.py", line 10, in <module>
    import bluesky.ui.qtgl.glhelpers as glh
AttributeError: module 'bluesky' has no attribute 'ui'

**Comment by jooste** [comment]
The zmq error is caused by a zombie bluesky process that is still running from a previous session. Check with `ps -aux | grep python` to find the process ids, and kill them. The ui error might be caused by that as well. let's see :)

**Comment by hemjyoti** [comment]
After killing the process, the zmq error is solved but not the ui error. I get the following error now:

Reading magnetic variation data
Found Qt-provided OpenGL functions for OpenGL (4, 1) Core
Traceback (most recent call last):
  File "BlueSky.py", line 115, in <module>
    main()
  File "BlueSky.py", line 98, in main
    from bluesky.ui import qtgl
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.glhelpers import (gl, RenderObject, RenderTarget, RenderWidget,
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/__init__.py", line 2, in <module>
    from bluesky.ui.qtgl.gui import start
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/gui.py", line 9, in <module>
    from bluesky.ui.qtgl.mainwindow import MainWindow, Splash, DiscoveryDialog
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/mainwindow.py", line 21, in <module>
    from bluesky.ui.qtgl.radarwidget import RadarWidget
  File "/home/hemjyoti/Twente/reinforcement_learning/Python3_codes/bluesky/bluesky/ui/qtgl/radarwidget.py", line 10, in <module>
    import bluesky.ui.qtgl.glhelpers as glh
AttributeError: module 'bluesky' has no attribute 'ui'
Reading config from settings.cfg
Loading global navigation database...
Reading cache: data/cache/py3/navdata.p
Failed to load BADA performance model
Successfully loaded plugin AREA
Successfully loaded plugin DATAFEED

**Comment by jooste** [comment]
Hmm, I don't know why this goes wrong on your machine. I'll look into it when I have more time.

**Comment by jooste** [comment]
Ok, so it turns out that this is an issue with the importing system in python <= 3.6.x! I managed to work around it by changing some of the import statements, implemented in commit 63d0911. This should resolve your issue!

**Comment by hemjyoti** [comment]
Thank so much professor! It worked with the latest commit.  Closing the issue now.
