### ISSUE TITLE
Another numpy math function error

### ISSUE THREAD

**Issue by andubadea** [TUDelft-CNS-ATM/bluesky#302]
Hello,

I just downloaded a fresh new copy of Bluesky, and when I try to run it, I get the following error:

```Traceback (most recent call last):
  File "C:\Users\andub\git\bluesky\Bluesky.py", line 115, in <module> 
    main()
  File "C:\Users\andub\git\bluesky\Bluesky.py", line 76, in main      
    bs.init(mode, discovery=discovery, cfgfile=cfgfile, scnfile=scnfile)
  File "C:\Users\andub\git\bluesky\bluesky\__init__.py", line 54, in init
    navdb = Navdatabase()
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\navdatabase.py", line 45, in __init__
    self.reset()
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\navdatabase.py", line 49, in reset
    wptdata, aptdata, awydata, firdata, codata, rwythresholds = load_navdata()
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\loadnavdata.py", line 33, in load_navdata
    rwythresholds = loadthresholds_txt()
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\loadnavdata_txt.py", line 401, in loadthresholds_txt
    thr0 = thresholds(np.radians(lat0), np.radians(lon0),
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\loadnavdata_txt.py", line 427, in thresholds
    latthres, lonthres = thrpoints(lat1, lon1, d, bearing)
  File "C:\Users\andub\git\bluesky\bluesky\navdatabase\loadnavdata_txt.py", line 436, in thrpoints
    latthres = np.asin(np.sin(lat1) * np.cos(d) + np.cos(lat1) * np.sin(d) * np.cos(bearing))
  File "C:\Users\andub\miniconda3\lib\site-packages\numpy\__init__.py", line 313, in __getattr__
    raise AttributeError("module {!r} has no attribute "AttributeError: module 'numpy' has no attribute 'asin'
```

I assume this went under the radar as this code is only run once upon freshly installing Bluesky.

**Comment by jooste** [comment]
It looks like your copy is not as fresh as you think; this was fixed a week ago in commit 6bbb379!
