### ISSUE TITLE
error when creating a second aircraft

### ISSUE THREAD

**Issue by amorfinv** [TUDelft-CNS-ATM/bluesky#317]
Hello,

There appears to be an issue when creating a second aircraft with `CRE`. I get the following message when trying to add a second aircraft to simulation: 

```
Traceback (most recent call last):
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/stack/simstack.py", line 81, in process
    success, echotext = cmdobj(argstring)
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/stack/cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/traffic/traffic.py", line 281, in cre
    self.create_children(n)
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/core/trafficarrays.py", line 101, in create_children
    child.create(n)
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/traffic/performance/openap/perfoap.py", line 178, in create
    self.vmin[-n:], self.vmax[-n:] = self._construct_v_limits(self.actype[-1:], self.phase[-n:])
  File "/Users/localadmin/Desktop/andresmorfin/bluesky-master/bluesky/traffic/performance/openap/perfoap.py", line 393, in _construct_v_limits
    vmin[ir] = vminr
IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by jooste** [comment]
Thanks! Fixed in 24eb4f3.
