### ISSUE TITLE
Changing newtrack command in MVP function causes Error with RESET function

### ISSUE THREAD

**Issue by TiagoMMNunes** [TUDelft-CNS-ATM/bluesky#368]
I am implementing a simplified conflict solver that works by probing different heading angles and finding one that would lead to the conflict being solved. For a two aircraft scenario this outputs a a resolution command of format [HDG1 HDG2], i.e. the same format that is achieved through the line:

`newtrack = (np.arctan2(newv[0,:],newv[1,:])*180/np.pi) % 360`

In the MVP.py file (line 220 of the file). 

Simply changing this line to 

`newtrack = new_aircraft_tracks` 

Causes the Reset function to fail when called through the stack commands. The BlueSky terminal will then output:

`Error calling function implementation of RESET:
Traceback printed to terminal`

Please find bellow the traceback of the error

Traceback (most recent call last):
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\stack\simstack.py", line 81, in process
    success, echotext = cmdobj(argstring)
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\simulation\simulation.py", line 160, in reset
    bs.traf.reset()
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\traffic\traffic.py", line 170, in reset
    super().reset()
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\core\trafficarrays.py", line 125, in reset
    child.reset()
  File "C:\Users\tmmonteironune\Desktop\bluesky-master\bluesky\core\trafficarrays.py", line 128, in reset
    self.__dict__[v] = np.array([], dtype=self.__dict__[v].dtype)
AttributeError: 'list' object has no attribute 'dtype'

The odd part is that, when my code tries to initialize the next scenario with a new aircraft of the same name, BlueSky says that aircraft already exists (I assume because reset failed). But the Add Waypoint command (Which i use at the start of each episode to set a target waypoint) doesnt work either and with the same error message

![image](https://user-images.githubusercontent.com/92160874/153231115-3a390555-7559-4c1a-af49-334e32c9bae6.png)

Likewise, the traceback for the Addwaypoint error. 
`Traceback (most recent call last):
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\BlueSky DQFD\bluesky-master\bluesky\stack\simstack.py", line 81, in process
    success, echotext = cmdobj(argstring)
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\BlueSky DQFD\bluesky-master\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
  File "C:\Users\tmmonteironune\Desktop\Coding and scripts\BlueSky DQFD\bluesky-master\bluesky\traffic\route.py", line 203, in addwptStack
    if acrte.nwp == 0:
AttributeError: 'NoneType' object has no attribute 'nwp'`

I have tried to resolve this error by defaulting the _newtrack_ command to the MVP whenever ntraf == 0 but that doesn't seem to work. I have also tried attempted several other fixes. I have even tried to implement my heading solver function into the MVP file as a function there and to simply keep all things the same except for the one line where my solution is inputted instead of MVP's and this also does not work. I am not sure what else to try to get this to work, can you please help me? Thank you in advance

**Comment by jooste** [comment]
Hi @TiagoMMNunes, it looks like you update the resolution tracks with a list instead of a NumPy array, which is what the Resolution base class expects. See if the error persists if you try the following:
```python
   newtrack = np.array(new_aircraft_tracks)
```
