### ISSUE TITLE
BlueSky Pip install issue (Windows)

### ISSUE THREAD

**Issue by Ellislee1** [TUDelft-CNS-ATM/bluesky#415]
I'm once again having an issue with installing BlueSky through pip, this time on Windows 11. 

I currently have python version `3.10.6` and have installed bluesky through an elevated terminal (power shell) using the command `pip install bluesky-simulator[full]`

This is the error I get:
```
PS C:\Users\Ellis> bluesky
Traceback (most recent call last):
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\Scripts\bluesky.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'BlueSky'
```

When running the alternative command `python -m bluesky` I get a different error:

```
PS C:\Users\Ellis> python -m bluesky
Traceback (most recent call last):
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\__main__.py", line 75, in <module>
    sys.exit(main())
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\__main__.py", line 35, in main
    bs.init(**args)
AttributeError: module 'bluesky' has no attribute 'init'
```

And then sometimes I get:
``` 
PS C:\Users\Ellis> python -m bluesky
Using Python-based geo functions
Reading config from C:\Users\Ellis\bluesky\settings.cfg
Reading magnetic variation data
Traceback (most recent call last):
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\__main__.py", line 75, in <module>
    sys.exit(main())
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\__main__.py", line 35, in main
    bs.init(**args)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\__init__.py", line 66, in init
    tools.init()
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\tools\__init__.py", line 20, in init
    geo.initdecl_data()
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\bluesky\tools\geo.py", line 496, in initdecl_data
    dec_table = np.genfromtxt(settings.resolve_path(settings.navdata_path) / 'geo_declination_data.csv',
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\npyio.py", line 1793, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\site-packages\numpy\lib\_datasource.py", line 533, in open
    raise IOError("%s not found." % path)
OSError: C:\Users\Ellis\bluesky\data\navdata\geo_declination_data.csv not found.
```
 
(Which seems to be my most common error)

**Comment by jooste** [comment]
Hi @Ellislee1,

Thanks for the information.

The first two errors are related to the fact that you are running from your home directory, where there is also a directory called `bluesky`. This then interferes with the `import bluesky` statement. I still need a good fix for this.

The third error just means that not all current datafiles are present in your local bluesky dir. These files are copied there when you start bluesky for the first time. However, once the `bluesky` folder exists in your home directory bluesky assumes that all required files are present, which in this case is not true. I guess we also need a better check for that :)

**Comment by jooste** [comment]
Update: when I try running `bluesky` or `python -m bluesky` from my home folder bluesky starts with no issues. Did you install the most recent pip package? It could be that this issue is windows-specific.

**Comment by Ellislee1** [comment]
So I did a complete reinstall of python (for an unrelated issue) and reinstalled bluesky with just `pip install bluesky-simulator[full]`
Similar to a previous issue I had on OSX I did have to manually go and delete some phantom bluesky folders in `C:/Users/<username>` likely from an outdated install that was not previously removed. 

I still get the error when I run `bluesky` from anywhere but as you mentioned this is a known issue.
```
C:\>bluesky
Traceback (most recent call last):
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\Ellis\AppData\Local\Programs\Python\Python310\Scripts\bluesky.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'BlueSky'
```

But running `python -m bluesky` a couple of times did finally get it working (I had some weird crash outs with no error messages, I thought it was related to generating the binaries/files that were created but not found initially?).

**Comment by jooste** [comment]
Thanks for the update. In the mean time I've been looking more into this on a windows pc. The no module named 'BlueSky' I haven't seen yet, but it seems to indicate a problem with the entry point on windows. I am updating the data folder initialisation code to allow you to update the data folder.

There can be a crash without a clear error once, when you start the gui for the first time. This has to do with an opengl init taking too long (when generating the polygon data). This is fixed on the master version, but hasn't made its way yet to a package release.

**Comment by jooste** [comment]
Ok, have a look at v2022.08.23 on pypi. It contains the following changes:

- Removed BlueSky.py as entrypoint, in favour of bluesky.__main__.main (hopefully a fix to the 'no module named BlueSky' error)
- Added a command-line option that allows you to update the `bluesky` folder in your home directory, to make it up-to-date with the current version of bluesky

Let me know if this fixes (any of) your problems!

**Comment by Ellislee1** [comment]
Thanks @jooste, this seems to have fixed all the problems I had. I can now enter bluesky from the home directory using only `bluesky`.

Many thanks!

**Comment by jooste** [comment]
Great! Thanks for testing :)
