### ISSUE TITLE
The installation doesnt work 

### ISSUE THREAD

**Issue by Madaa29** [TUDelft-CNS-ATM/bluesky#423]
Hello ! 

When i'm trying to install Bluesky with the pip install on an Ubuntu 22.04 command the following result appears : 

`mada@mada:~/Desktop$ pip install bluesky-simulator[full]
Defaulting to user installation because normal site-packages is not writeable
Collecting bluesky-simulator[full]
  Downloading bluesky-simulator-2022.8.26.tar.gz (52.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.0/52.0 MB 30.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-yhxj80f8/bluesky-simulator_e09a2feb593d43f4b7e584b5d3d362dd/setup.py", line 34, in <module>
          shutil.copytree('data', 'bluesky/resources/data', ignore=shutil.ignore_patterns('cache'))
        File "/usr/lib/python3.10/shutil.py", line 554, in copytree
          with os.scandir(src) as itr:
      FileNotFoundError: [Errno 2] No such file or directory: 'data'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
`

Thank you for your time

**Comment by jooste** [comment]
Hi @Madaa29,

I think this is because the 2022.8.26 release on pip was incomplete. I removed it for now. Could you try to install v2022.8.23?

**Comment by Madaa29** [comment]
Hello ! 

The download is now working but now the map screen is black and the map don't appears 
In the console log i get those messages : 

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__main__.py", line 75, in <module>
    sys.exit(main())
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__main__.py", line 35, in main
    bs.init(**args)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__init__.py", line 99, in init
    traf = Traffic()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/core/entity.py", line 58, in __call__
    cls._instance = super().__call__(*args, **kwargs)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/traffic/traffic.py", line 141, in __init__
    self.perf     = PerfBase()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/core/entity.py", line 73, in __call__
    cls.selected()._instance = super().__call__(*args, **kwargs)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/traffic/performance/openap/perfoap.py", line 25, in __init__
    self.coeff = coeff.Coefficient()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/traffic/performance/openap/coeff.py", line 23, in __init__
    with open(settings.resolve_path(settings.perf_path_openap) / 'synonym.dat', "r") as f_syno:
```

**Comment by jooste** [comment]
It looks like the bottom part of the traceback is missing! But I think I can see what's going wrong: I think you have an incomplete `bluesky` dir in your home. try running bluesky with the argument `--updatedirs`, and let it copy the directories it needs.

FYI: this whole directory copying and linking approach is planned to be replaced, hopefully by something that is more robust :)

**Comment by Madaa29** [comment]
Just done it and Bluesky don't work anymore :(
```
mada@mada:~/.local/bin$ python3 -m bluesky --updatedirs
Using Python-based geo functions
Copying default configfile to /home/mada/bluesky/settings.cfg
Replace /home/mada/bluesky/settings.cfg with newer /home/mada/.local/lib/python3.10/site-packages/bluesky/resources/data/default.cfg? [y/N/a]: y
Creating directory "/home/mada/bluesky/output"
Creating directory "/home/mada/bluesky/data/cache"
Creating directory "/home/mada/bluesky/data/performance"
Creating directory "/home/mada/bluesky/scenario", and copying default files
Creating directory "/home/mada/bluesky/plugins", and copying default files
Creating directory "/home/mada/bluesky/data/performance/BADA", and copying default files
Reading config from /home/mada/bluesky/settings.cfg
Reading magnetic variation data
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__main__.py", line 75, in <module>
    sys.exit(main())
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__main__.py", line 35, in main
    bs.init(**args)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__init__.py", line 66, in init
    tools.init()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/tools/__init__.py", line 20, in init
    geo.initdecl_data()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/tools/geo.py", line 496, in initdecl_data
    dec_table = np.genfromtxt(settings.resolve_path(settings.navdata_path) / 'geo_declination_data.csv',
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/npyio.py", line 1934, in genfromtxt
    fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/_datasource.py", line 193, in open
    return ds.open(path, mode, encoding=encoding, newline=newline)
  File "/usr/local/lib/python3.10/dist-packages/numpy/lib/_datasource.py", line 533, in open
    raise FileNotFoundError(f"{path} not found.")
FileNotFoundError: /home/mada/bluesky/data/data/navdata/geo_declination_data.csv not found.
```

**Comment by jooste** [comment]
That's indeed a known error (and one of the reasons we're planning to make some changes). I think the easiest workaround is to make the file available where it is erroneously looking. Assuming that the `bluesky` folder is now correctly populated you could try the following:
```
ln -s ~/bluesky/data/data ~/bluesky/data
```

**Comment by Madaa29** [comment]
Still doesn't working :/ 

```
mada@swag:~/.local/bin$ ./bluesky 
Using Python-based geo functions
Reading config from /home/mada/bluesky/settings.cfg
Reading magnetic variation data
Traceback (most recent call last):
  File "/usr/lib/python3.10/pathlib.py", line 1085, in resolve
    p.stat()
  File "/usr/lib/python3.10/pathlib.py", line 1095, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
OSError: [Errno 40] Too many levels of symbolic links: '/home/mada/bluesky/data/data/navdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mada/.local/bin/./bluesky", line 8, in <module>
    sys.exit(main())
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__main__.py", line 35, in main
    bs.init(**args)
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/__init__.py", line 66, in init
    tools.init()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/tools/__init__.py", line 20, in init
    geo.initdecl_data()
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/tools/geo.py", line 496, in initdecl_data
    dec_table = np.genfromtxt(settings.resolve_path(settings.navdata_path) / 'geo_declination_data.csv',
  File "/home/mada/.local/lib/python3.10/site-packages/bluesky/settings.py", line 31, in resolve_path
    return path if path.is_absolute() else (_basepath / path).resolve()
  File "/usr/lib/python3.10/pathlib.py", line 1087, in resolve
    check_eloop(e)
  File "/usr/lib/python3.10/pathlib.py", line 1072, in check_eloop
    raise RuntimeError("Symlink loop from %r" % e.filename)
RuntimeError: Symlink loop from '/home/mada/bluesky/data/data/navdata'
```

**Comment by jooste** [comment]
Hi @Madaa29,

An update after a bit of radio silence: I've made several changes to the way bluesky populates and uses the bluesky resources directory in your home folder. Could you please try the following:

- Erase ~/bluesky (backup first if you have custom scenarios or plugins there)
- Install the latest pypi package of bluesky-simulator[full] (v2022.9.18)
- Try to run `bluesky`
I hope this gets you further!

**Comment by Madaa29** [comment]
Hello ! 

Thank you for the update but there is a problem :(

On a fresh new vm  when I install I have a problem with pyqt

![image](https://user-images.githubusercontent.com/58108819/190980575-71f4484b-f02a-434a-87c7-fd3c47e14105.png)

Thank you for the reply !

**Comment by jooste** [comment]
right, in that case you can use Qt5:

`pip install "bluesky-simulator[qt5]"`

**Comment by Madaa29** [comment]
By using qt5 the installation is complete but when i lauch it i have the following errors : 

![image](https://user-images.githubusercontent.com/58108819/190984601-753f6fe4-a234-4a25-8f26-baf2091c6ecb.png)

**Comment by jooste** [comment]
Thanks. Apparently `files()` is only part of `importlib.resources` since python 3.9. I've added a requirement for `importlib_resources` for python versions < 3.9, and modified the import statement to try and fix this.

The result should be available on pypi as version 2022.9.19.

**Comment by Madaa29** [comment]
The patch solves this problem and now I can install the package but when i try to launch the app I get an error from qt who cannot launch the app 

![image](https://user-images.githubusercontent.com/58108819/191017822-f1bd07e3-70e0-4270-aa8d-d915bc0f4479.png)

**Comment by jooste** [comment]
This is not a problem with bluesky, but with your (py)qt installation. Googling for the error gives a lot of hits. The first step to pinpoint the root error is to set a debugging environment variable before starting the qt application (bluesky in this case):

```
export QT_DEBUG_PLUGINS=1
bluesky
```
This should give you a much more verbose error. A frequent error with pip-installed Qt on linux is `_ZN11QFontEngine14bitmapForGlyphEj6QFixedRK10QTransform`. If you have this then the pip-installed Qt libs are mixing with Qt libs that are elsewhere on your system. I don't think the fix is easy though.

Just to confirm:
- How did you install python? (from python.org, anaconda, os package manager)
- Are you running in a VM?
- Can you check if you have other versions of Qt installed? (eg with rpm or apt)

**Comment by Madaa29** [comment]
It works ! 

I was on an Ubuntu 20.04  so I download a 22.04 Ubuntu on VmWare ! 

I did the following commands : 

```
sudo apt update && sudo apt upgrade -y
sudo apt install python3-pip
sudo apt-get install build-essential libgl1-mesa-dev
pip install numpy
pip install bluesky-simulator[full]
```

I then launch bluesky by going into my .local/bin files and I tried to run it with the python3 -m command and it works too ! 

Thank you a lot for your help on this ! 

I have some more questions if you have time ! Is it possible by mail ? 

Thank you again :) !

**Comment by jooste** [comment]
Sure, you can send me a mail! 
And thank you too, it's difficult to debug multiple platforms without feedback, so your comments are appreciated!

**Comment by Madaa29** [comment]
I don't find your email :/ 
No problem !

**Comment by Madaa29** [comment]
Thank you !
