### ISSUE TITLE
Error in the installation

### ISSUE THREAD

**Issue by Madaa29** [TUDelft-CNS-ATM/bluesky#442]
Hello, 
Since the last update the installation doesn't work anymore on an Ubuntu 20.04.
Here is the errors that i get. 

`mada@mada-VirtualBox:~/Desktop$ python3 -m bluesky
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 185, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 144, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/mada/.local/lib/python3.8/site-packages/bluesky/__init__.py", line 2, in <module>
    from bluesky import settings
  File "/home/mada/.local/lib/python3.8/site-packages/bluesky/settings.py", line 4, in <module>
    from bluesky.pathfinder import resource
  File "/home/mada/.local/lib/python3.8/site-packages/bluesky/pathfinder.py", line 107, in <module>
    resource.path = ResourcePath()
  File "/home/mada/.local/lib/python3.8/site-packages/bluesky/pathfinder.py", line 37, in __init__
    base = files('bluesky.resources')
  File "/home/mada/.local/lib/python3.8/site-packages/bluesky/pathfinder.py", line 19, in files
    return Path(p.args[0].path).parent / p.args[1]
AttributeError: 'str' object has no attribute 'path'`

Thank you for your response!

**Comment by jooste** [comment]
Hi @Madaa29,

This importlib.resources has been giving us some headaches ;) I've just committed an alternative that is hopefully more robust. If it works out on other platforms as well we'll create a new package.

**Comment by Madaa29** [comment]
I tried to install it this morning with the latest package and it still gives me the same error.

**Comment by jooste** [comment]
I assume you are using the (pip) packaged version of BlueSky? It hasn't been updated yet with the fix from yesterday. I want to be sure first that it works :)

**Comment by jooste** [comment]
Ok, a new version was just uploaded to pypi. Let us know if it is still causing errors for you!

**Comment by Madaa29** [comment]
Hello ! It's working ! The only issue is to open scenario it doesn't work !
Thank you a lot ! :)

**Comment by jooste** [comment]
Can you be more specific? What are you trying exactly, and what then happens?

**Comment by Madaa29** [comment]
When you want to launch a scenario by clicking on "open" nothing is happening and we have the following error 
![image](https://user-images.githubusercontent.com/58108819/209096182-27e83cb9-8140-45ef-8782-7ff856971e82.png)
![image](https://user-images.githubusercontent.com/58108819/209096493-170d7b32-bdb5-4c73-afd5-f7125c43f311.png)

**Comment by jooste** [comment]
Ah, thanks, that was a remaining bug in the transition to PyQt6. Should be fixed in the latest release.
