### ISSUE TITLE
ADDWPT not working

### ISSUE THREAD

**Issue by madhumnk** [TUDelft-CNS-ATM/bluesky#473]
After running ADDWPT KL001 COA 

Error calling function implementation of ADDWPT: 'numpy.float64' object cannot be interpreted as a terminal. 

As the same code was working yesterday and not today, after freshly installing the blue sky it is adding the waypoint path but the aircraft is not moving towards the point specified.

**Comment by madhumnk** [comment]
![ADDWPT](https://github.com/TUDelft-CNS-ATM/bluesky/assets/66828355/b5390446-f6d5-45c9-b2a2-45ad1b926214)

**Comment by madhumnk** [comment]
![ORIG](https://github.com/TUDelft-CNS-ATM/bluesky/assets/66828355/23631ca0-269a-46bc-87dc-6645cf504bff)

Same error for ORIG command too

**Comment by madhumnk** [comment]
Hello @jooste, Thanks for your response. 
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 389, in addwptStack
    acrte.direct(acidx, acrte.wpname[norig])  # 0 if no orig
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 373, in addwptStack
    wpidx = acrte.addwpt(acidx, name, wptype, lat, lon, alt, spd, afterwp, beforewp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 373, in addwptStack
    wpidx = acrte.addwpt(acidx, name, wptype, lat, lon, alt, spd, afterwp, beforewp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 389, in addwptStack
    acrte.direct(acidx, acrte.wpname[norig])  # 0 if no orig
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 373, in addwptStack
    wpidx = acrte.addwpt(acidx, name, wptype, lat, lon, alt, spd, afterwp, beforewp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\autopilot.py", line 798, in setorig
    iwp = route.addwpt(acidx, self.orig[acidx], route.orig,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 373, in addwptStack
    wpidx = acrte.addwpt(acidx, name, wptype, lat, lon, alt, spd, afterwp, beforewp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\autopilot.py", line 750, in setdest
    iwp = route.addwpt(acidx, self.dest[acidx], route.dest,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\simstack.py", line 79, in process
    success, echotext = cmdobj(argstring)
                        ^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\stack\cmdparser.py", line 83, in __call__
    ret = self.callback(*args)
          ^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\autopilot.py", line 798, in setorig
    iwp = route.addwpt(acidx, self.orig[acidx], route.orig,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 899, in addwpt
    self.direct(iac, self.wpname[self.iactwp])
  File "X:\MPDS\Bluesky\bluesky\bluesky\traffic\route.py", line 983, in direct
    turnrad*abs(tan(0.5*radians(max(5., abs(degto180(qdr_ -
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 2810, in max
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\madhu\anaconda3\envs\bluesky\Lib\site-packages\numpy\core\fromnumeric.py", line 88, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'numpy.float64' object cannot be interpreted as an integer


-----------------------------------------------------------------------------------

commands I used - 
![Command-1](https://github.com/TUDelft-CNS-ATM/bluesky/assets/66828355/61b75743-7ff3-42b1-9fa4-9da2f3610d3b)
![Command-2](https://github.com/TUDelft-CNS-ATM/bluesky/assets/66828355/c9cf16e7-43d0-4689-8874-c058f79b746a)

-----------------------------------------------------
I have installed Python from python.org , python version is 3.11.4

**Comment by madhumnk** [comment]
Followed steps from https://github.com/TUDelft-CNS-ATM/bluesky/wiki/Installation#Source-install to install the Bluesky.

Actually It was working fine when I used before, now the same command is throwing error.

**Comment by jooste** [comment]
Thanks. This has to do with a recent change in NumPy, that has made it more strict. I proposed a fix in the route-numpy branch. Once this is reviewed it will also become available in the main branch.

**Comment by madhumnk** [comment]
Ok! Thank you.

**Comment by jooste** [comment]
Fixed in d3d0a24. Thanks for posting!
